export const DEFAULT_CATEGORIES = [
  "Histoire",
  "Géographie",
  "Physique / Chimie",
  "Biologie",
  "Langues 🇫🇷 / 🇬🇧",
  "Littérature",
  "Philosophie",
  "Psychologie",
  "Droit",
  "Économie",
  "Politique",
  "Informatique",
  "Technologie",
  "Médecine",
  "Musique",
  "Cinéma",
  "Art",
  "Sport",
  "Mathématiques",
  "Astronomie",
  "Autre",
]